# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kbnuRyFsNQ9Lhs8KgQpa-i3Yku-A97bK
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
import time
import random

def intervals(jobs):
    jobs.sort(key=lambda x: x[1])
    n = len(jobs)
    dp = [0] * (n + 1)

    for i in range(1, n + 1):
        current = jobs[i-1]
        last_compatible = -1
        for j in range(i-1, 0, -1):
            if jobs[j-1][1] <= current[0]:
                last_compatible = j
                break
        dp[i] = dp[i-1]
        if last_compatible != -1:
            dp[i] = max(dp[i], current[2] + dp[last_compatible])
        else:
            dp[i] = max(dp[i], current[2])
    return dp[n]

def generate_jobs(n):
    return [(random.randint(0, 100), random.randint(10, 200), random.randint(1, 10)) for _ in range(n)]


sizes = [100, 200, 400, 600, 800, 1000]
results = {}

for n in sizes:
    times = []
    for _ in range(20):
        jobs = generate_jobs(n)
        start = time.time()
        intervals(jobs)
        times.append(time.time() - start)
    results[n] = (np.mean(times), np.std(times))
    print(f"n={n}: μ={results[n][0]:.4f}, σ={results[n][1]:.4f}")

plt.figure(figsize=(12, 4))

plt.subplot(121)
n_vals = list(results.keys())
means = [r[0] for r in results.values()]
stds = [r[1] for r in results.values()]

plt.plot(n_vals, means, 'b-', linewidth=2, label='Среднее время')
plt.fill_between(n_vals,
                  [means[i] - 2*stds[i] for i in range(len(n_vals))],
                  [means[i] + 2*stds[i] for i in range(len(n_vals))],
                  alpha=0.3, label='±2σ')
plt.xlabel('Размер входных данных (n)')
plt.ylabel('Время выполнения (сек)')
plt.title('Зависимость времени от n')
plt.grid(alpha=0.3)
plt.legend()

n_chosen = 800
times_chosen = []
for _ in range(150):
    jobs = generate_jobs(n_chosen)
    start = time.time()
    intervals(jobs)
    times_chosen.append(time.time() - start)

plt.subplot(122)
plt.hist(times_chosen, bins=15, edgecolor='black', alpha=0.7, density=True)
plt.xlabel('Время выполнения (сек)')
plt.ylabel('Плотность вероятности')
plt.title(f'Гистограмма времени для n={n_chosen}')

mu, sigma = np.mean(times_chosen), np.std(times_chosen)
x = np.linspace(min(times_chosen), max(times_chosen), 100)
plt.plot(x, stats.norm.pdf(x, mu, sigma), 'r-', linewidth=2, label='Нормальное распределение')
plt.legend()

shapiro_p = stats.shapiro(times_chosen)[1]
print(f"\nТест Шапиро-Уилка p-value={shapiro_p:.4f}")
print("Гипотеза о нормальном распределении: " + ("ПРИНИМАЕТСЯ" if shapiro_p > 0.05 else "ОТВЕРГАЕТСЯ"))

plt.tight_layout()
plt.show()